const createFooter = () => {
	const footer = document.createElement('footer');
	const footerImgContainer = document.createElement('div');
	footerImgContainer.classList.add('footer-img');
	footerImgContainer.classList.add('mb-medium');
	const footerImg = document.createElement('img');
	footerImg.src = 'https://i.ibb.co/QkSxXDf/12.png';
	footerImg.alt = 'photo with sushi and rolls';
	footerImgContainer.appendChild(footerImg);
	const footerTextContainer = document.createElement('div');
	footerTextContainer.classList.add('footer-text');
	const h2El = document.createElement('h2');
	h2El.innerHTML = 'Get in touch';
	footerTextContainer.appendChild(h2El);
	const column1 = document.createElement('div');
	column1.classList.add('footer-text-column');
	const column2 = document.createElement('div');
	column2.classList.add('footer-text-column');
	footer.appendChild(footerImgContainer);
	const column1Paragraph = document.createElement('p');
	column1Paragraph.innerHTML = '856-948-1459';
	const column2Paragraph = document.createElement('p');
	column2Paragraph.innerHTML = 'hello@reallygreatsite.com';
	const column1Header = document.createElement('h4');
	column1Header.innerHTML = 'Phone number';
	const column2Header = document.createElement('h4');
	column2Header.innerHTML = 'E-mail address';
	column1.appendChild(column1Header);
	column1.appendChild(column1Paragraph);
	column2.appendChild(column2Header);
	column2.appendChild(column2Paragraph);
	footerTextContainer.appendChild(column1);
	footerTextContainer.appendChild(column2);
	footer.appendChild(footerTextContainer);
	return footer;
};
export default createFooter;
